### ISSUE TITLE
Following up on blog post questions

### ISSUE THREAD

**Issue by jwosty** [CompositionalIT/SAFE-FSharp.Logf#1]
Hi Matt,

Nice to see a blog post and sample repo for FSharp.Logf + SAFE integration - much appreciated! I see that you had some questions/concerns at the end of the post. 

> There's still some things I'd want to explore before considering using it in production, for example how well it works with our preferred logging library, Serilog.

My own projects are using Serilog as the logging provider. You should be able to use it with anything that can expose itself as a `Microsoft.Extensions.Logging.ILogger`. I wrote a few sentences about that here: https://github.com/jwosty/FSharp.Logf/issues/1. Perhaps that needs to go in the README - unless you had other concerns about Serilog compatibility? (I can even say that Serilog gives you better formatting than the framework-included logger - for example when printing an array with the console formatter, the former prints the actual contents whereas the latter just prints the type).

> In addition, I'm wary of adding new dependencies, and I don't know that the utility this library offers warrants bringing on a new one.

That's fair; it is a relatively simple library by design. I encourage you to experiment with it in a more complete codebase. If there's anything that would fit as an addition to this library, please [feel free to open up an issue](https://github.com/jwosty/FSharp.Logf/issues).

**Comment by mattgallagher92** [comment]
Hey @jwosty, thanks for taking the time to respond, and sorry I missed it!

With regards to Serilog, I just wanted to highlight to readers that I haven't done that exploration. Not saying that there are any problems, just that they may want to check that out first.

I've added a link in the post to this issue, so that interested readers can see your response :slightly_smiling_face:
